name: bdd-testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v0.0.0
        
    - name: Setup Chromedriver
      uses: apt-get install chromedriver
    
    - name: Test
      run: go test -v ./... -json > reports/test-report.json
