name: bdd-testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - uses: browser-actions/setup-chrome@latest
      run: chrome --version

    - uses: actions/checkout@v2
    - uses: nanasess/setup-chromedriver@v1
    - run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

    - name: Test
      # run: go test -v ./... -json > reports/test-report.json
      run: go test -v ./... 